Fix for: WARNING: Please set conf.dot15d4_protocol to select a 802.15…
mingqian/zigbee-viewer pull request #2
Opened 2022-01-02 13:09 UTC by talpadk

Seems like newer versions of scapy requires that one selects the protocol decode on the 802.15.4 
This change configures selects zigbee as the protocol

2022-03-11 07:47 UTC, phe-sto approved these changes

2022-03-11 07:47 UTC, phe-sto approved these changes

2022-03-11 09:28 UTC, phe-sto commented
If the `try/except` is in the loop which is in my opinion should be the case, you can use enumerate on `pkts` and avoid declaring `packetIndex` variable, which one syntax is by the way not Pythonic. Python favor snake_case over camelCase.

2022-03-11 09:33 UTC, phe-sto requested changes
Nest the `try/except` in the loop and use `enumerate` to avoid to declare `packetIndex` this way but rather declare `packet_index, p = enumerate(pkts)` in the `try/except`.

2022-03-14 09:00 UTC, mingqian commented
Cherry-pick this PR and merged. Thanks.

2022-03-14 09:00 UTC, closed without merging